### ISSUE TITLE
[RFE] newdoc option to omit internal content

### ISSUE THREAD

**Issue by rkratky** [redhat-documentation/tools#13]
It would be useful to have an option for `newdoc` to omit the inclusion of the content governed by the `internal` attribute. For some upstream uses, this metadata is redundant.

**Comment by VladimirSlavik** [comment]
It might be nice to see some data on actual usage of that part. I'd guess most people treat it as noise, same as the "this module included in assemblies" comment...

**Comment by msuchane** [comment]
With https://github.com/redhat-documentation/tools/pull/24, the templates no longer include the internal content.
