### ISSUE TITLE
[RFE] newdoc capability to create assemblies with include:: statements ready

### ISSUE THREAD

**Issue by rkratky** [redhat-documentation/tools#14]
It would be great if `newdoc` could generate assemblies populated with `include::` statements based on either a series of command-line options (specifying the assembly and its modules), or an input file.

CLI options:

`newdoc --populate -a assembly.adoc -c concept.adoc -p procedure.adoc -r reference.adoc`

Or an input file:

```
$ cat input.txt
a assembly.adoc
c concept.adoc
p procedure.adoc
r reference.adoc
```
`newdoc --populate --inputfile input.txt`

Both of these examples would generate `assembly.adoc` with the following:

```
$ cat assembly.adoc
[...snip...]
include::concept.adoc[leveloffset=+1]
include::procedure.adoc[leveloffset=+1]
include::reference.adoc[leveloffset=+1]
[...snip...]
```

It should be possible to define multiple assemblies.

(I ended up scripting my own solution to this in Bash, so I could share if deemed useful.)

**Comment by msuchane** [comment]
@rkratky, the new version of `newdoc` (https://github.com/redhat-documentation/newdoc/) now has support for populating an assembly using the `--include-in` option.

Can we close this issue?

**Comment by rkratky** [comment]
Yup, thanks!
