### ISSUE TITLE
[Buig] [newdoc] crashes when file already exists

### ISSUE THREAD

**Issue by rkratky** [redhat-documentation/tools#15]
When running `newdoc` in a directory that contains a file with a name same as what `newdoc` is attempting to create, the script crashes. It would be nice if it instead offered to overwrite or keep the existing file. E.g.:

```
File called 'proc_module.adoc' already exists.
(o)verwrite, (k)eep, (O)verwrite all, (K)eep all
```
Or something similar.

But for starters, it could just fail gracefully, listing the offending file.

**Comment by VladimirSlavik** [comment]
It does that for me already. Perhaps I have newer version? Where did you get yours from? I run the version installed with pip a few days ago and it asks:

```
File already exists: "assembly_blah.adoc"
Overwrite it? [yes/no] n
Preserving the older file.
```

edit: Just to clarify, what I'm getting at is that perhaps it's a bug in distribution rather than code :)

**Comment by rkratky** [comment]
I use Marek's COPR repo. Will test with a newer version.

**Comment by msuchane** [comment]
@rkratky, could you please test if this bug still happens with the updated packages that I've just released?

**Comment by rkratky** [comment]
Works as expected. Thanks.
