### ISSUE TITLE
[Bug] [newdoc] Update the templates to match the ones in the modular-docs repository

### ISSUE THREAD

**Issue by jhradilek** [redhat-documentation/tools#18]
The `newdoc` script currently uses built-in templates.  These were originally based on those in the [modular-docs](https://github.com/redhat-documentation/modular-docs/tree/master/modular-docs-manual/files) repository, but are now outdated. Please update the templates produced by `newdoc` to match the official ones.

**Comment by msuchane** [comment]
The content of the templates is updated so I'm closing this issue.

There's still the question of how to handle file name prefixes but I'd prefer to track it in https://github.com/redhat-documentation/tools/issues/8.
