### ISSUE TITLE
[Bug] [atree] Readme is missing multiple output warnings

### ISSUE THREAD

**Issue by pbokoc** [redhat-documentation/tools#20]
The output of atree can contain warnings in front of filenames that aren't documented in the README:

* R! = (infinitely) recursive include
* X! = invalid for some reason
* N! = file does not exist

**Comment by pbokoc** [comment]
Also, `-b` ignores these which should be mentioned in that option's description.

**Comment by VladimirSlavik** [comment]
@pbokoc , are you open to reviewing the pull request in #23 ? That should solve this.

**Comment by pbokoc** [comment]
@VladimirSlavik Looks good to me, thanks!
