### ISSUE TITLE
Optional step

### ISSUE THREAD

**Issue by JoanneOFlynn2018** [redhat-documentation/tools#29]
suggested changes for the procedure template:
To align with IBM style guide, instead of (Optional) use Optional:

**Comment by ncbaratta** [comment]
Which tool are you specifically reporting this issue for?

**Comment by JoanneOFlynn2018** [comment]
Apologies, this is for the newdoc tool Nicole. thanks!

**Comment by msuchane** [comment]
Thanks for letting me know. I'll fix it in newdoc as soon as possible.

**Comment by msuchane** [comment]
I've released updates packages of newdoc 1.5.0, which includes a fix for the optional step.
