### ISSUE TITLE
[Bug] [newdoc] newdoc creates {context} after it has been used

### ISSUE THREAD

**Issue by vikram-redhat** [redhat-documentation/tools#7]
On line https://github.com/redhat-documentation/tools/blame/master/newdoc/newdoc/templates/assembly_title.adoc#L34 of the template, the context variable is defined. However, it is already used before that on line 28: https://github.com/redhat-documentation/tools/blame/master/newdoc/newdoc/templates/assembly_title.adoc#L28.

This causes the build to fail as aura tries to decipher moduleid_{context} instead of the actual context value that should be substituted. 

Solution would be to line 34 before line 28. That is, define the context value before using it.

The other larger issue, of course, is that the templates are out of sync with the actual templates defined in the mod docs repo. Is there a way to keep these in sync?

**Comment by rkratky** [comment]
> The other larger issue, of course, is that the templates are out of sync with the actual templates defined in the mod docs repo. Is there a way to keep these in sync?

@mrksu  As discussed previously, it would really be much better if the script didn't rely on templates in this repo (which can easily fall out of date) but on the official templates in the mod docs repo [1].

[1] https://github.com/redhat-documentation/modular-docs/tree/master/modular-docs-manual/files

**Comment by VladimirSlavik** [comment]
That makes a lot of sense, for a tool that is supposed to be universal...

**Comment by VladimirSlavik** [comment]
@vikram-redhat you're saying it is used without definition. In the scope of a single file, that's true. But it is supposed to come from the other file including this one, so that's why it is not defined there.

You can also use your own templates easily...

**Comment by msuchane** [comment]
@vikram-redhat, could you please check if this is still an issue with the updated templates that were merged in https://github.com/redhat-documentation/tools/pull/24?

**Comment by msuchane** [comment]
I believe that this issue has been fixed, as I suggested in my last comment. Closing.
