### ISSUE TITLE
[RFE] [newdoc] Add a command line option to not have filename prefixes

### ISSUE THREAD

**Issue by vikram-redhat** [redhat-documentation/tools#8]
Since https://github.com/redhat-documentation/modular-docs/pull/61 was merged, the guideline is NOT to use proc, con, ref and assembly as part of the filenames. I understand some teams want to still use that, and that is perfectly ok. However, since most teams would be following the official guidelines, which do not recommend the use of these prefixes, it would be good if we can provide this as a command line option to include/exclude (whichever is easier).

**Comment by pwright** [comment]
newdoc is it's own repo now, closing as out of date
